name: default
kind: pipeline
type: docker

platform:
  os: linux
  arch: amd64

steps:
- name: test-backend
  image: openjdk:8-jdk-slim
  commands:
  - cd ./api
  - ./mvnw clean install
  - ./mvnw test

- name: test-frontend
  image: mhart:alpine-node:12
  commands:
  - cd ./ui
  - npm install
  - npm test

trigger:
  branch:
  - master
  event:
  - pull_request
