name: default
kind: pipeline
type: docker

platform:
  os: linux
  arch: amd64

steps:
- name: test-backend
  image: openjdk:11-jdk-slim
  commands:
  - cd ./api
  - ./mvnw clean install
  - ./mvnw test -P test

- name: test-frontend
  image: mhart/alpine-node:12
  commands:
  - cd ./ui
  - npm install
  - npm lint
  - npm test

trigger:
  branch:
  - master
  event:
  - pull_request
