name: default
kind: pipeline
type: docker

platform:
  os: linux
  arch: amd64

steps:
- name: test-backend
  image: openjdk:11-jdk-slim
  commands:
  - cd ./api
  - ./mvnw clean install
  - ./mvnw test -P it

- name: test-frontend
  image: mhart/alpine-node:12
  commands:
  - cd ./ui
  - npm install
  - npm run-script lint
  - npm test

services:
- name: db
  image: postgres:13-alpine
  environment:
    POSTGRES_DB: kimosabe
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: admin

- name: redis
  image: redislabs/redisearch:latest

- name: populate-redis
  image: plugins/docker
  insecure: true
  environment:
    REDIS_HOST: redis
  settings:
    repo: 6rotoms/igdb-pdt

trigger:
  branch:
  - master
  event:
  - pull_request
