version: '3.5'
services:
  db:
    restart: always
    image: postgres:13-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=kimosabe
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    networks:
      - kimosabe

  redis:
    restart: always
    image: redislabs/redisearch:latest
    ports:
      - '6379:6379'
    networks:
      - kimosabe

  populate-redis:
    restart: always
    image: 6rotom/igdb-pdt
    ports:
      - '6400:6400'
    networks:
      - kimosabe

networks:
    kimosabe:
        name: kimosabe
