version: '3.5'
services:
  db:
    container_name: db
    restart: always
    image: postgres:13-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=kimosabe
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    networks:
      - kimosabe

  redis:
    container_name: redis
    restart: always
    image: redislabs/redisearch:latest
    ports:
      - '6379:6379'
    networks:
      - kimosabe

  populate-redis:
    container_name: populate-redis
    restart: always
    image: 6rotom/igdb-pdt:latest
    ports:
      - '6400:6400'
    networks:
      - kimosabe

  mailserver:
    container_name: mailhog
    restart: always
    image: mailhog/mailhog:latest
    ports:
      - '1025:1025'
      - '8025:8025'
    networks:
      - kimosabe

networks:
    kimosabe:
        name: kimosabe
