version: '3'
services:
  db:
    restart: always
    image: postgres:13-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=kimosabe
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin

  redis:
    restart: always
    image: redislabs/redisearch:latest
    ports:
      - '6379:6379'
  populate-redis:
    restart: always
    image: 6rotom/igdb-pdt:v0.3.2
    ports:
      - '6400:6400'
