version: '3.5'
services:
  redis:
    container_name: redis
    restart: always
    image: redislabs/redisearch:latest
    ports:
      - '6379:6379'
    networks:
      - kimosabe

  populate-redis:
    container_name: populate-redis
    restart: always
    image: 6rotom/igdb-pdt:latest
    ports:
      - '6400:6400'
    networks:
      - kimosabe

networks:
    kimosabe:
        name: kimosabe
